### ISSUE TITLE
Feature #1: User can view products

### ISSUE THREAD

**Issue by j-alejandro-araujo** [j-alejandro-araujo/Art_eCommerce#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view products (utilize READ from CRUD).

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can visit homepage, click on products to view catalogue of multiple products and click into a specific item for more details.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screenshot 2023-07-31 at 12 11 21 PM](https://github.com/j-alejandro-araujo/Art_eCommerce/assets/91649194/a5b33efa-f82f-4b50-94ca-07915939821b)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `schema.sql` to include new tables.
- [x] Update `data.sql` to include products that will fill database tables.

### ☁️ Server Tasks

- [x] Update `server.js` to implement READ functionality from CRUD. 
- [x] Test with HTTPie and make sure no errors occur.
- [x] Handle all errors and respond to the client.
- [x] Make sure READ works correctly and returns requested data.

### ⚡ Client Tasks

- [x] Create a component to display product catalogue to user. 
- [x] Update component when user clicks on a product, it should render product details. 

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that all data fetched from the server is handled correctly and displayed without errors.
- [x] Ensure the products are displayed efficiently w/ focus on UI.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
